### ISSUE TITLE
Convenience functions for GET, POST, etc.

### ISSUE THREAD

**Issue by gamache** [appcues/mojito#10]
In addition to `Mojito.request/5`, we should provide convenience functions for `head/3`, `get/3`, `post/4`, `put/4`, `patch/4`, `delete/3`, and `options/3`.  People like those.

**Comment by danhuynhdev** [comment]
@gamache I implemented this in PR #20. Hope to get your feedback.

**Comment by gamache** [comment]
Implemented in 0.3.0.
