### ISSUE TITLE
Passing in a nil URL returns a hard-to-debug error

### ISSUE THREAD

**Issue by AnilRedshift** [appcues/mojito#11]
Calling `Mojito.request(:get, nil) will return the following error: 
```
{:error,
 %Mojito.Error{
   message: nil,
   reason: %FunctionClauseError{
     args: nil,
     arity: 2,
     clauses: nil,
     function: :from_string,
     kind: nil,
     module: Fuzzyurl
   }
 }}
```

I somewhat expected Dialyzer to pick this up, but it didn't at least for my project. It would be better in my opinion to add a guard clause preventing this somewhat common user behavior. Doing so would generate an easy to understand error message. I will open a PR to consider for this issue

**Comment by gamache** [comment]
0.1.1 fixes this.  Thanks again!
