### ISSUE TITLE
Document that by default you will receive tcp messages in the process that calls `Mojito.request`

### ISSUE THREAD

**Issue by axelson** [appcues/mojito#18]
From a slack discussion with @gamache 

> gamache   [9 hours ago]
> That's correct, the caller process will receive messages of the form `{:tcp, _, _}` and `{:ssl, _, _}` and handle them transparently.
>
> gamache   [9 hours ago]
> Other messages will be left in the mailbox, which should keep most callers out of trouble, but if other TCP/SSL messages were expected, Mojito will gobble them up.  In that case, wrap the one-off request in a Task or use Mojito.Pool to make requests.

I think this should be called out on the docs at https://hexdocs.pm/mojito/0.2.1/Mojito.html#request/1 and https://hexdocs.pm/mojito/0.2.1/Mojito.html#request/5

And the module doc could probably be a little more explicit as well.

**Comment by gamache** [comment]
You're absolutely right, I will document this better.  It's in the module docs, but I will add it to the function docs as well.

**Comment by axelson** [comment]
Great, thanks!
