### ISSUE TITLE
Follow redirect

### ISSUE THREAD

**Issue by sntran** [appcues/mojito#21]
Support option to `follow_redirect` and return the response at the final location.

**Comment by gamache** [comment]
Solid idea.  We'll add this.

**Comment by ntenczar** [comment]
Hi! This project is now deprecated:

We recommend that you use [Finch](https://github.com/sneako/finch) which is also built on [Mint](https://github.com/ericmj/mint). The creator of Finch has an [excellent writeup here](https://elixirforum.com/t/mint-vs-finch-vs-gun-vs-tesla-vs-httpoison-etc/38588/11) describing the problems with Mojito, and as a result we use Finch internally at Appcues now.
