### ISSUE TITLE
Discussion: Mojito should not use the application environment

### ISSUE THREAD

**Issue by josevalim** [appcues/mojito#23]
Hi @gamache!

Just a quick topic for discussion. From the README, it seems Mojito is using the application environment / config files to configure its pools. The problem with this design is that it is not composable.

For example, imagine I want to write a library called "foobar" that needs to use Mojito. Now if someone wants to use my "foobar" library in their application, they need to explicitly configure Mojito inside their app, because it is not possible (by design) for one library to configure the environment of another library in behalf of an application.

You could argue that the application may most likely to configure the pool anyway, which is a good point, but that may not always be the case and the current design always forces me to. Similarly, as the author of "foobar", I may not want to leak to my users that I am actually using Mojito, as it is an implementation detail, and currently it seems I don't have the option.

## Possible solution: how to configure pools

One option to configure pools is to have users explicitly start pools in their app:

    [
      {Mojito.Pool, name: MyApp.Pool, ...}
    }

And now when doing the request you pass which pool to use: `Mojito.get(MyApp.Pool, ...)`. This gives users complete control when the pools are started and configured.

You may still want to provide a built-in, no-host pool, when Mojito is started, which is configured via the application environment, but it should be absolutely clear that the config of this pool will be shared across all libraries and apps.

PS: Note I am writing this report based on the README, so if any of it is inaccurate, apologies and close this issue. :)

**Comment by gamache** [comment]
Hello José! Thanks for bringing this up.

You are correct that Mojito currently requires configuration through the application environment.  This is a bug, not a feature, for the reasons you mention.

However, I don't want Mojito users to absorb the responsibility of starting pools and matching requests to the correct pool.  In fact, I have removed this mode of operation from the public API.  Handling this automatically is a primary design goal of Mojito.

The interface I have in mind is to pass the `pool_opts` option to `Mojito.request/1` and merge the config there with the results of `Application.get_env(:mojito, :pool_opts, [])`, like:

`Mojito.request(method: :get, url: "https://example.com", opts: [pool_opts: [size: 64, pools: 4]])`

The `pool_opts` will be used during the first request to a given destination, and ignored thereafter.

This does not work today but can be made to work with some relatively simple edits to `Mojito.Pool` and `Mojito.Pool.Manager`.

**Comment by ntenczar** [comment]
Hi! This project is now deprecated:

We recommend that you use [Finch](https://github.com/sneako/finch) which is also built on [Mint](https://github.com/ericmj/mint). The creator of Finch has an [excellent writeup here](https://elixirforum.com/t/mint-vs-finch-vs-gun-vs-tesla-vs-httpoison-etc/38588/11) describing the problems with Mojito, and as a result we use Finch internally at Appcues now.
