### ISSUE TITLE
Fragment handling in URI

### ISSUE THREAD

**Issue by alappe** [appcues/mojito#28]
At the moment, an existing fragment of the requested URI is passed down to mint. If I understand it correctly, this should not be the case. I checked with hackney, httpie and other tools and they all omit the fragment.

> Clients are not supposed to send URI fragments to servers when they retrieve a document, […]
https://en.wikipedia.org/wiki/Fragment_identifier

**Comment by gamache** [comment]
Hello @alappe! Sorry for the delayed reply, you caught me on vacation.  Thank you for this issue and PR -- it will be included in the next release.

**Comment by alappe** [comment]
Perfect, thanks :-)

**Comment by gamache** [comment]
Fixed in 0.4.0.  Thanks again!
