### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by esvinson** [appcues/mojito#36]
Is there currently a way to use the proxy functionality from Mint with Mojito, or does that still need to be implemented?

I'm not seeing any references to proxy support at the moment.

**Comment by gamache** [comment]
You should be able to pass the same `:proxy` config in the `opts` argument of `Mojito.request` and it will pass through to Mint. Can you report if this works as intended?

**Comment by esvinson** [comment]
Yep.  That seems to work, as well as Mint supports it, thank you!  I put in a PR for Mint to support passing headers to the TunnelProxy's connect to fix lack of Basic authentication support.

Example Mojito.request payload for anyone looking at this in the future:
```
Mojito.request(%{
  method: :get,
  url: "https://httpbin.org",
  opts: [
    pool: true,
    proxy: {:http, "localhost", 8888, []}
  ]
})
```

If ericmj/mint#218 gets merged the 4th tuple element `[]` could be replaced with `[headers: [{"proxy-authorization", "basic BASE64_ENCODED_USER:PASS"}]]` to handle basic authentication.
