### ISSUE TITLE
Allow configuring a default CA certificate file

### ISSUE THREAD

**Issue by bfad** [appcues/mojito#45]
Instead of using the `CAStore` package, I would like to be able to specify the location of the certificate file that is managed by my OS. It would be great if I could configure Mojito to use that by default instead and make the `CAStore` package an optional dependency.

I would like to be able to have the following code in my `config/config.exs` file:
```elixir
config :mojito, :cacertfile, "/etc/ssl/certs/ca-certificates.crt"
```
And then I would like all SSL connections to use that file unless the function call specifies something different in the `transport_opts` option.

I know this would be a breaking change that would require people currently using the package to either set the configuration or include `CAStore` as a dependency, so I thought I'd suggest it here before attempting to work on this myself.

**Comment by gamache** [comment]
Hi @bfad! Sorry for the late reply. I'm not keen on making this a breaking change, but I think making `:transport_opts` configurable in `config.exs` would be a good idea.  I'm currently refactoring Mojito's config system, and I will make sure this gets in there.

**Comment by ntenczar** [comment]
Hi! This project is now deprecated:

We recommend that you use [Finch](https://github.com/sneako/finch) which is also built on [Mint](https://github.com/ericmj/mint). The creator of Finch has an [excellent writeup here](https://elixirforum.com/t/mint-vs-finch-vs-gun-vs-tesla-vs-httpoison-etc/38588/11) describing the problems with Mojito, and as a result we use Finch internally at Appcues now.
