### ISSUE TITLE
Receiving `{:error, %Mint.TransportError{reason: :timeout}}`

### ISSUE THREAD

**Issue by lud** [appcues/mojito#56]
Hello, 

When we make a call with mojito that results in `{:error, %Mojito.Error{message: nil, reason: :checkout_timeout}}`, we receive a message like this: `{#Reference<0.981418250.3438280705.26871>, {:error, %Mint.TransportError{reason: :timeout}}}` after a while. 

It is not a big deal since we can handle those message and ignore them. But shouldn't mojito and mint have the same timeout ?

**Comment by andyleclair** [comment]
`:checkout_timeout` means that there's an issue checking a connection out from the pool

**Comment by gamache** [comment]
This sounds like it could be related to #57; @lud are you sure the messages are connected to the requests that received `:checkout_timeout`?

**Comment by lud** [comment]
@gamache unfortunately no, I am not 100% sure. I am not sure what you mean by "connected" but the message was received by the process (a `Phoenix.Channel` process) that made a request to a local PHP deveserver, ten-ish seconds after the request failed with `:checkout_timeout`.

**Comment by ntenczar** [comment]
Hi! This project is now deprecated:

We recommend that you use [Finch](https://github.com/sneako/finch) which is also built on [Mint](https://github.com/ericmj/mint). The creator of Finch has an [excellent writeup here](https://elixirforum.com/t/mint-vs-finch-vs-gun-vs-tesla-vs-httpoison-etc/38588/11) describing the problems with Mojito, and as a result we use Finch internally at Appcues now.
