### ISSUE TITLE
Feature: fail fast

### ISSUE THREAD

**Issue by i-n-g-m-a-r** [appcues/mojito#61]
Hi gamache, very nice project, I am looking for something almost exactly like this, mint + poolboy + simplicity, though I will also need a fail fast mechanism preferably a (sophisticated configurable) circuit breaker.
Do you have any thoughts on that or are you maybe even planning a feature like that?
I could put Mojito behind a circuit breaker of course, that may be even better, just interested in your thoughts.
For me it would be a killer feature.

**Comment by gamache** [comment]
Hello @i-n-g-m-a-r!  Right now there are no plans to add a circuit breaker to Mojito, though I completely agree with you on their value, and we would love having it as a feature if it were implemented in a performant way.

**Comment by ntenczar** [comment]
Hi! This project is now deprecated:

We recommend that you use [Finch](https://github.com/sneako/finch) which is also built on [Mint](https://github.com/ericmj/mint). The creator of Finch has an [excellent writeup here](https://elixirforum.com/t/mint-vs-finch-vs-gun-vs-tesla-vs-httpoison-etc/38588/11) describing the problems with Mojito, and as a result we use Finch internally at Appcues now.
