### ISSUE TITLE
More friendly API to deal with errors

### ISSUE THREAD

**Issue by mbenatti** [appcues/mojito#71]
I tested your library and notice that I can´t parse error response easily, because the library doesn't handle/parse it to a common contract.  

Example of errors doing requests:

```Elixir
%Mojito.Error{message: "invalid URL"}

%Mojito.Error{reason: %Mint.TransportError{reason: :nxdomain}}}
```

A common contract could be like this:

```Elixir
%Mojito.Error{reason: :invalid_url, message: "invalid URL"}

%Mojito.Error{reason: :nx_domain, details: %Mint.TransportError{reason: :nxdomain}}

%Mojito.Error{reason: :some_other_error}
```

**Comment by gamache** [comment]
Hi @mbenatti! You are absolutely correct that Mojito's errors need to take a more consistent shape. It's a breaking change, which is tough, but IMO this is something we need to solve prior to or as part of a 1.0 release. I'll keep this issue open to track progress.

**Comment by ntenczar** [comment]
Hi! This project is now deprecated:

We recommend that you use [Finch](https://github.com/sneako/finch) which is also built on [Mint](https://github.com/ericmj/mint). The creator of Finch has an [excellent writeup here](https://elixirforum.com/t/mint-vs-finch-vs-gun-vs-tesla-vs-httpoison-etc/38588/11) describing the problems with Mojito, and as a result we use Finch internally at Appcues now.
