### ISSUE TITLE
Mint with pool: false leaks HTTP connections like a sieve

### ISSUE THREAD

**Issue by bmteller** [appcues/mojito#82]
Search for `close` in Single (https://github.com/appcues/mojito/blob/master/lib/mojito/request/single.ex). There are no calls to `Mint.HTTP.close`. If the socket is not closed it is leaked until the process dies. see: https://hexdocs.pm/mint/Mint.HTTP.html#close/1

**Comment by andyleclair** [comment]
Closed in #83
