### ISSUE TITLE
Handling empty responses

### ISSUE THREAD

**Issue by mhmdkzr** [appcues/mojito#95]
Hi, I've noticed that Mojito tries to decompress a response even when it's empty, which will result in this error:
```
** (ErlangError) Erlang error: :data_error
    :zlib.inflateEnd_nif(#Reference<0.3283516080.844496899.227436>)
    :zlib.gunzip/1
    (mojito 0.7.9) lib/mojito.ex:7: Mojito.maybe_decompress/2
```
When the status code is 200, I think the expected behavior would be returning an empty response.

**Comment by mhmdkzr** [comment]
I found that this is actually a problem on the server side, because if server is sending empty response body, it shouldn't keep content-encoding headers of a gzip response, but in my case, it was. So it's not a problem caused by Mojito, but it can be handled by it. 
Out of curiosity, I tried this with [requests](https://github.com/psf/requests) library in python to see how it would handle this, and it gave me an empty response. [Req](https://github.com/wojtekmach/req/blob/5e3ac4e106df8c01d3a2748c471c1f062dff5e7a/lib/req.ex#L640) also seems to be doing the same. 
Just let me know if you decided to handle this case in Mojito, and I'll send a PR with tests for it.

**Comment by ntenczar** [comment]
Hi! This project is now deprecated:

We recommend that you use [Finch](https://github.com/sneako/finch) which is also built on [Mint](https://github.com/ericmj/mint). The creator of Finch has an [excellent writeup here](https://elixirforum.com/t/mint-vs-finch-vs-gun-vs-tesla-vs-httpoison-etc/38588/11) describing the problems with Mojito, and as a result we use Finch internally at Appcues now.
